version: '3.8'

services:
  database:
    image: postgres:16.1
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/sql/01-table-definition.sql:/docker-entrypoint-initdb.d/01-table-definition.sql
      - ./db/sql/02-data-insert.sql:/docker-entrypoint-initdb.d/02-data-insert.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  
  api:
    depends_on:
      - database
    build: api
    ports:
      - 8000:8000
    networks:
     - backend

  web:
    depends_on:
      - api
    build: web
    ports: 
      - 8080:80


networks:
  backend: