version: '3.8'

services:
  database:
    image: postgres:16.1
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - backend
  
  api:
    depends_on:
      - database
    build: api
    ports:
      - 8000:8000
    networks:
     - backend


networks:
  backend: